swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:  
{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: View all transactions
      description: API to view all transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
    
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized  
        "500":
          description: Internal Server Error

{accountId}/transactions/{transaction_id}:
    get :
      security:
        - Bearer: []
      tags:
        - Transactions details 
      summary: User transaction details
      description: API to view details of a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: User's account ID
          required: true
          type: string
        - name: transaction_id
          in: path
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

   patch :
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: Update user transaction
      description: API for updating transaction informations
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transaction_id
          description: Transaction id
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction informations
          required: true
          schema:
            $ref: "#/definitions/EditTransaction"
      produces:
        - application/json
      responses:
        "204":
          description: User transaction infos updated successully
          schema:
            $ref: "#/definitions/EditTransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Delete a transaction note
      description: API to delete a note
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transaction_id
          description: Transaction id
          required: true
          type: string

      produces:
        - application/json
      responses:
        "204":
          description: Delete completed successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
            format: date
          description:
            type: string
          amount:
            type: string
            format : currency
          balance:
            type: string
            format: currency
          transaction type:
            type: string
          category:
            type: string
          note:
            type: string
  Update transaction:
    type: object
    properties:
      category:
        type: string
      note:
        type: string
  Create note:
    type: object
    properties:
      note:
        type: string
  Delete transaction:
    type: object
    properties:
      note:
        type: string