swagger: "2.0"
info:
  description: "Bank API documentation for transactions"
  version: "1.0.0"
  title: "Argent Bank Transactions API Documentation"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/api/v1"
tags:
  - name: "transactions"
    description: "Operations to manage transactions"
schemes:
  - "http"
paths:
  /{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - "User Transactions"
      summary: "View all transactions"
      description: "API to view all transactions by account"
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          required: true
          type: string
        - name: accountId
          in: path
          description: "User's account ID"
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: "User transactions retrieved successfully"
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: "Invalid Account"
        "401":
          description: "Unauthorized, invalid token"
        "500":
          description: "Internal Server Error"

  /transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - "Transactions Details"
      summary: "User transaction details"
      description: "API to view details of a transaction"
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          required: true
          type: string
        - name: accountId
          in: path
          description: "User's account ID"
          required: true
          type: string
        - name: transaction_id
          in: path
          description: "Transaction ID"
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: "Transaction details retrieved successfully"
          schema:
            $ref: "#/definitions/TransactionsResponse"
        '400':
          description: "Invalid account or transaction ID"
        '401':
          description: "Unauthorized, invalid token"
        '500':
          description: "Internal Server Error"

  /{accountId}/transactions/{transaction_id}/:
    patch:
      security:
        - Bearer: []
      tags:
        - "User Transactions Module"
      summary: "Update user transaction"
      description: "API for updating transaction information"
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT token"
          required: true
          type: string
        - in: path
          name: transaction_id
          description: "Transaction ID"
          required: true
          type: string
        - in: body
          name: body
          description: "Update transaction information"
          required: true
          schema:
            $ref: "#/definitions/EditTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: "User transaction info updated successfully"
          schema:
            $ref: "#/definitions/EditTransactionResponse"
        "400":
          description: "Invalid Fields"
        "401":
          description: "Unauthorized, invalid token"
        "403":
          description: "Unauthorized, user not allowed to update this transaction"
        "500":
          description: "Internal Server Error"

    delete:
      security:
        - Bearer: []
      tags:
        - "User Transactions"
      summary: "Delete a transaction note"
      description: "API to delete a note"
      parameters:
        - in: header
          name: Authorization
          description: "Attach Bearer JWT Token"
          required: true
          type: string
        - in: path
          name: transaction_id
          description: "Transaction ID"
          required: true
          type: string
      produces:
        - application/json
      responses:
        "204":
          description: "Delete completed successfully"
        "400":
          description: "Invalid Fields"
        "401":
          description: "Unauthorized, invalid token"
        "403":
          description: "Unauthorized, user not allowed to delete this transaction"
        "500":
          description: "Internal Server Error"

securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"

definitions:
  TransactionsResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      message:
        type: "string"
      body:
        type: "object"
  EditTransaction:
    type: "object"
    properties:
      category:
        type: "string"
      note:
        type: "string"
  EditTransactionResponse:
    type: "object"
    properties:
      note:
        type: "string"

